/*
 * Copyright (c) 2013 Dennis Fischer.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0+
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/gpl.html
 *
 * Contributors: Dennis Fischer
 */

/**
 * This class is generated by jOOQ
 */
package de.chaosfisch.google.youtube;

import de.chaosfisch.google.account.Account;

import java.io.Serializable;
import java.util.GregorianCalendar;

public class Playlist implements Serializable {

	private static final long serialVersionUID = 1215529732;

	private Integer           id;
	private String            pkey;
	private Boolean           private_;
	private String            title;
	private String            url;
	private String            thumbnail;
	private Integer           number;
	private String            summary;
	private Boolean           hidden;
	private GregorianCalendar dateOfModified;
	private Account           account;

	public Integer getId() {
		return this.id;
	}

	public void setId(final Integer id) {
		this.id = id;
	}

	public String getPkey() {
		return this.pkey;
	}

	public void setPkey(final String pkey) {
		this.pkey = pkey;
	}

	public Boolean getPrivate() {
		return this.private_;
	}

	public void setPrivate(final Boolean private_) {
		this.private_ = private_;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(final String title) {
		this.title = title;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(final String url) {
		this.url = url;
	}

	public String getThumbnail() {
		return this.thumbnail;
	}

	public void setThumbnail(final String thumbnail) {
		this.thumbnail = thumbnail;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(final Integer number) {
		this.number = number;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(final String summary) {
		this.summary = summary;
	}

	public Boolean getHidden() {
		return this.hidden;
	}

	public void setHidden(final Boolean hidden) {
		this.hidden = hidden;
	}

	public GregorianCalendar getDateOfModified() {
		return this.dateOfModified;
	}

	public void setDateOfModified(final GregorianCalendar dateOfModified) {
		this.dateOfModified = dateOfModified;
	}

	public Account getAccount() {
		return account;
	}

	public void setAccount(final Account account) {
		this.account = account;
	}
}
