/*
 * Copyright (c) 2013 Dennis Fischer.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0+
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/gpl.html
 *
 * Contributors: Dennis Fischer
 */

/**
 * This class is generated by jOOQ
 */
package org.chaosfisch.youtubeuploader.db;

import org.chaosfisch.google.youtube.*;

public class Template extends org.chaosfisch.youtubeuploader.db.AbstractTemplate implements java.io.Serializable {

	private static final long serialVersionUID = -261086693;

	private Integer       id;
	private Category      category;
	private Comment       comment;
	private Boolean       commentvote;
	private java.io.File  defaultdir;
	private String        description;
	private Boolean       embed;
	private String        keywords;
	private String        name;
	private Boolean       rate;
	private Videoresponse videoresponse;
	private Visibility    visibility;
	private Integer       accountId;
	private java.io.File  enddir;
	private License       license;
	private String        title;
	private String        thumbnail;
	private Boolean       facebook;
	private Boolean       twitter;
	private String        message;
	private Boolean       monetizeInstreamDefaults;
	private Boolean       monetizeClaim;
	private Boolean       monetizeOverlay;
	private Boolean       monetizeTrueview;
	private Boolean       monetizeInstream;
	private Boolean       monetizeProduct;
	private Syndication   monetizeSyndication;
	private String        monetizeTitle;
	private String        monetizeDescription;
	private String        monetizeId;
	private String        monetizeNotes;
	private String        monetizeTmsid;
	private String        monetizeIsan;
	private String        monetizeEidr;
	private String        monetizeTitleepisode;
	private String        monetizeSeasonNb;
	private String        monetizeEpisodeNb;
	private ClaimType     monetizeClaimtype;
	private ClaimOption   monetizeClaimoption;
	private Asset         monetizeAsset;
	private Boolean       monetizePartner;

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public Comment getComment() {
		return this.comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

	public Boolean getCommentvote() {
		return this.commentvote;
	}

	public void setCommentvote(Boolean commentvote) {
		this.commentvote = commentvote;
	}

	public java.io.File getDefaultdir() {
		return this.defaultdir;
	}

	public void setDefaultdir(java.io.File defaultdir) {
		this.defaultdir = defaultdir;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getEmbed() {
		return this.embed;
	}

	public void setEmbed(Boolean embed) {
		this.embed = embed;
	}

	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getRate() {
		return this.rate;
	}

	public void setRate(Boolean rate) {
		this.rate = rate;
	}

	public Videoresponse getVideoresponse() {
		return this.videoresponse;
	}

	public void setVideoresponse(Videoresponse videoresponse) {
		this.videoresponse = videoresponse;
	}

	public Visibility getVisibility() {
		return this.visibility;
	}

	public void setVisibility(Visibility visibility) {
		this.visibility = visibility;
	}

	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	public java.io.File getEnddir() {
		return this.enddir;
	}

	public void setEnddir(java.io.File enddir) {
		this.enddir = enddir;
	}

	public License getLicense() {
		return this.license;
	}

	public void setLicense(License license) {
		this.license = license;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getThumbnail() {
		return this.thumbnail;
	}

	public void setThumbnail(String thumbnail) {
		this.thumbnail = thumbnail;
	}

	public Boolean getFacebook() {
		return this.facebook;
	}

	public void setFacebook(Boolean facebook) {
		this.facebook = facebook;
	}

	public Boolean getTwitter() {
		return this.twitter;
	}

	public void setTwitter(Boolean twitter) {
		this.twitter = twitter;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Boolean getMonetizeInstreamDefaults() {
		return this.monetizeInstreamDefaults;
	}

	public void setMonetizeInstreamDefaults(Boolean monetizeInstreamDefaults) {
		this.monetizeInstreamDefaults = monetizeInstreamDefaults;
	}

	public Boolean getMonetizeClaim() {
		return this.monetizeClaim;
	}

	public void setMonetizeClaim(Boolean monetizeClaim) {
		this.monetizeClaim = monetizeClaim;
	}

	public Boolean getMonetizeOverlay() {
		return this.monetizeOverlay;
	}

	public void setMonetizeOverlay(Boolean monetizeOverlay) {
		this.monetizeOverlay = monetizeOverlay;
	}

	public Boolean getMonetizeTrueview() {
		return this.monetizeTrueview;
	}

	public void setMonetizeTrueview(Boolean monetizeTrueview) {
		this.monetizeTrueview = monetizeTrueview;
	}

	public Boolean getMonetizeInstream() {
		return this.monetizeInstream;
	}

	public void setMonetizeInstream(Boolean monetizeInstream) {
		this.monetizeInstream = monetizeInstream;
	}

	public Boolean getMonetizeProduct() {
		return this.monetizeProduct;
	}

	public void setMonetizeProduct(Boolean monetizeProduct) {
		this.monetizeProduct = monetizeProduct;
	}

	public Syndication getMonetizeSyndication() {
		return this.monetizeSyndication;
	}

	public void setMonetizeSyndication(Syndication monetizeSyndication) {
		this.monetizeSyndication = monetizeSyndication;
	}

	public String getMonetizeTitle() {
		return this.monetizeTitle;
	}

	public void setMonetizeTitle(String monetizeTitle) {
		this.monetizeTitle = monetizeTitle;
	}

	public String getMonetizeDescription() {
		return this.monetizeDescription;
	}

	public void setMonetizeDescription(String monetizeDescription) {
		this.monetizeDescription = monetizeDescription;
	}

	public String getMonetizeId() {
		return this.monetizeId;
	}

	public void setMonetizeId(String monetizeId) {
		this.monetizeId = monetizeId;
	}

	public String getMonetizeNotes() {
		return this.monetizeNotes;
	}

	public void setMonetizeNotes(String monetizeNotes) {
		this.monetizeNotes = monetizeNotes;
	}

	public String getMonetizeTmsid() {
		return this.monetizeTmsid;
	}

	public void setMonetizeTmsid(String monetizeTmsid) {
		this.monetizeTmsid = monetizeTmsid;
	}

	public String getMonetizeIsan() {
		return this.monetizeIsan;
	}

	public void setMonetizeIsan(String monetizeIsan) {
		this.monetizeIsan = monetizeIsan;
	}

	public String getMonetizeEidr() {
		return this.monetizeEidr;
	}

	public void setMonetizeEidr(String monetizeEidr) {
		this.monetizeEidr = monetizeEidr;
	}

	public String getMonetizeTitleepisode() {
		return this.monetizeTitleepisode;
	}

	public void setMonetizeTitleepisode(String monetizeTitleepisode) {
		this.monetizeTitleepisode = monetizeTitleepisode;
	}

	public String getMonetizeSeasonNb() {
		return this.monetizeSeasonNb;
	}

	public void setMonetizeSeasonNb(String monetizeSeasonNb) {
		this.monetizeSeasonNb = monetizeSeasonNb;
	}

	public String getMonetizeEpisodeNb() {
		return this.monetizeEpisodeNb;
	}

	public void setMonetizeEpisodeNb(String monetizeEpisodeNb) {
		this.monetizeEpisodeNb = monetizeEpisodeNb;
	}

	public ClaimType getMonetizeClaimtype() {
		return this.monetizeClaimtype;
	}

	public void setMonetizeClaimtype(ClaimType monetizeClaimtype) {
		this.monetizeClaimtype = monetizeClaimtype;
	}

	public ClaimOption getMonetizeClaimoption() {
		return this.monetizeClaimoption;
	}

	public void setMonetizeClaimoption(ClaimOption monetizeClaimoption) {
		this.monetizeClaimoption = monetizeClaimoption;
	}

	public Asset getMonetizeAsset() {
		return this.monetizeAsset;
	}

	public void setMonetizeAsset(Asset monetizeAsset) {
		this.monetizeAsset = monetizeAsset;
	}

	public Boolean getMonetizePartner() {
		return this.monetizePartner;
	}

	public void setMonetizePartner(Boolean monetizePartner) {
		this.monetizePartner = monetizePartner;
	}
}
