/**************************************************************************************************
 * Copyright (c) 2014 Dennis Fischer.                                                             *
 * All rights reserved. This program and the accompanying materials                               *
 * are made available under the terms of the GNU Public License v3.0+                             *
 * which accompanies this distribution, and is available at                                       *
 * http://www.gnu.org/licenses/gpl.html                                                           *
 *                                                                                                *
 * Contributors: Dennis Fischer                                                                   *
 **************************************************************************************************/

/**
 * This class is generated by jOOQ
 */
package de.chaosfisch.google.account;

import de.chaosfisch.google.playlist.PlaylistModel;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleListProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;

import static de.chaosfisch.google.http.PersistentCookieStore.SerializableCookie;

public class AccountModel {

	private final SimpleIntegerProperty                  id                  = new SimpleIntegerProperty();
	private final SimpleStringProperty                   name                = new SimpleStringProperty();
	private final SimpleStringProperty                   email               = new SimpleStringProperty();
	private final SimpleStringProperty                   refreshToken        = new SimpleStringProperty();
	private final SimpleObjectProperty<AccountType>      type                = new SimpleObjectProperty<>();
	private final SimpleListProperty<PlaylistModel>      playlists           = new SimpleListProperty<>(FXCollections.observableArrayList());
	private final SimpleListProperty<SerializableCookie> serializableCookies = new SimpleListProperty<>(FXCollections.observableArrayList());

	public String getEmail() {
		return email.get();
	}

	public void setEmail(final String email) {
		this.email.set(email);
	}

	public SimpleStringProperty emailProperty() {
		return email;
	}

	public int getId() {
		return id.get();
	}

	public void setId(final int id) {
		this.id.set(id);
	}

	public SimpleIntegerProperty idProperty() {
		return id;
	}

	public SimpleStringProperty nameProperty() {
		return name;
	}

	public String getRefreshToken() {
		return refreshToken.get();
	}

	public void setRefreshToken(final String refreshToken) {
		this.refreshToken.set(refreshToken);
	}

	public SimpleStringProperty refreshTokenProperty() {
		return refreshToken;
	}

	public AccountType getType() {
		return type.get();
	}

	public void setType(final AccountType type) {
		this.type.set(type);
	}

	public SimpleObjectProperty<AccountType> typeProperty() {
		return type;
	}

	public ObservableList<PlaylistModel> getPlaylists() {
		return playlists.get();
	}

	public void setPlaylists(final ObservableList<PlaylistModel> playlists) {
		this.playlists.set(playlists);
	}

	public SimpleListProperty<PlaylistModel> playlistsProperty() {
		return playlists;
	}

	public ObservableList<SerializableCookie> getSerializableCookies() {
		return serializableCookies.get();
	}

	public void setSerializableCookies(final ObservableList<SerializableCookie> serializableCookies) {
		this.serializableCookies.set(serializableCookies);
	}

	public SimpleListProperty<SerializableCookie> serializableCookiesProperty() {
		return serializableCookies;
	}

	@Override
	public String toString() {
		return getName();
	}

	public String getName() {
		return name.get();
	}

	public void setName(final String name) {
		this.name.set(name);
	}
}
