/*
 * Copyright (c) 2013 Dennis Fischer.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0+
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/gpl.html
 *
 * Contributors: Dennis Fischer
 */

/**
 * This class is generated by jOOQ
 */
package de.chaosfisch.youtubeuploader.db;

import de.chaosfisch.google.youtube.upload.metadata.License;
import de.chaosfisch.google.youtube.upload.metadata.permissions.*;

import java.io.File;
import java.io.Serializable;

public class Template extends AbstractTemplate implements Serializable {

	private static final long serialVersionUID = -261086693;

	private Integer       id;
	private Category      category;
	private Comment       comment;
	private Boolean       commentvote;
	private File          defaultdir;
	private String        description;
	private Boolean       embed;
	private String        keywords;
	private String        name;
	private Boolean       rate;
	private Videoresponse videoresponse;
	private Visibility    visibility;
	private Integer       accountId;
	private File          enddir;
	private License       license;
	private String        title;
	private String        thumbnail;
	private Boolean       facebook;
	private Boolean       twitter;
	private String        message;
	private Boolean       monetizeInstreamDefaults;
	private Boolean       monetizeClaim;
	private Boolean       monetizeOverlay;
	private Boolean       monetizeTrueview;
	private Boolean       monetizeInstream;
	private Boolean       monetizeProduct;
	private Syndication   monetizeSyndication;
	private String        monetizeTitle;
	private String        monetizeDescription;
	private String        monetizeId;
	private String        monetizeNotes;
	private String        monetizeTmsid;
	private String        monetizeIsan;
	private String        monetizeEidr;
	private String        monetizeTitleepisode;
	private String        monetizeSeasonNb;
	private String        monetizeEpisodeNb;
	private ClaimType     monetizeClaimtype;
	private ClaimOption   monetizeClaimoption;
	private Asset         monetizeAsset;
	private Boolean       monetizePartner;

	@Override
	public Integer getId() {
		return id;
	}

	public void setId(final Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return category;
	}

	public void setCategory(final Category category) {
		this.category = category;
	}

	public Comment getComment() {
		return comment;
	}

	public void setComment(final Comment comment) {
		this.comment = comment;
	}

	public Boolean getCommentvote() {
		return commentvote;
	}

	public void setCommentvote(final Boolean commentvote) {
		this.commentvote = commentvote;
	}

	public File getDefaultdir() {
		return defaultdir;
	}

	public void setDefaultdir(final File defaultdir) {
		this.defaultdir = defaultdir;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(final String description) {
		this.description = description;
	}

	public Boolean getEmbed() {
		return embed;
	}

	public void setEmbed(final Boolean embed) {
		this.embed = embed;
	}

	public String getKeywords() {
		return keywords;
	}

	public void setKeywords(final String keywords) {
		this.keywords = keywords;
	}

	@Override
	public String getName() {
		return name;
	}

	public void setName(final String name) {
		this.name = name;
	}

	public Boolean getRate() {
		return rate;
	}

	public void setRate(final Boolean rate) {
		this.rate = rate;
	}

	public Videoresponse getVideoresponse() {
		return videoresponse;
	}

	public void setVideoresponse(final Videoresponse videoresponse) {
		this.videoresponse = videoresponse;
	}

	public Visibility getVisibility() {
		return visibility;
	}

	public void setVisibility(final Visibility visibility) {
		this.visibility = visibility;
	}

	public Integer getAccountId() {
		return accountId;
	}

	public void setAccountId(final Integer accountId) {
		this.accountId = accountId;
	}

	public File getEnddir() {
		return enddir;
	}

	public void setEnddir(final File enddir) {
		this.enddir = enddir;
	}

	public License getLicense() {
		return license;
	}

	public void setLicense(final License license) {
		this.license = license;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(final String title) {
		this.title = title;
	}

	public String getThumbnail() {
		return thumbnail;
	}

	public void setThumbnail(final String thumbnail) {
		this.thumbnail = thumbnail;
	}

	public Boolean getFacebook() {
		return facebook;
	}

	public void setFacebook(final Boolean facebook) {
		this.facebook = facebook;
	}

	public Boolean getTwitter() {
		return twitter;
	}

	public void setTwitter(final Boolean twitter) {
		this.twitter = twitter;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(final String message) {
		this.message = message;
	}

	public Boolean getMonetizeInstreamDefaults() {
		return monetizeInstreamDefaults;
	}

	public void setMonetizeInstreamDefaults(final Boolean monetizeInstreamDefaults) {
		this.monetizeInstreamDefaults = monetizeInstreamDefaults;
	}

	public Boolean getMonetizeClaim() {
		return monetizeClaim;
	}

	public void setMonetizeClaim(final Boolean monetizeClaim) {
		this.monetizeClaim = monetizeClaim;
	}

	public Boolean getMonetizeOverlay() {
		return monetizeOverlay;
	}

	public void setMonetizeOverlay(final Boolean monetizeOverlay) {
		this.monetizeOverlay = monetizeOverlay;
	}

	public Boolean getMonetizeTrueview() {
		return monetizeTrueview;
	}

	public void setMonetizeTrueview(final Boolean monetizeTrueview) {
		this.monetizeTrueview = monetizeTrueview;
	}

	public Boolean getMonetizeInstream() {
		return monetizeInstream;
	}

	public void setMonetizeInstream(final Boolean monetizeInstream) {
		this.monetizeInstream = monetizeInstream;
	}

	public Boolean getMonetizeProduct() {
		return monetizeProduct;
	}

	public void setMonetizeProduct(final Boolean monetizeProduct) {
		this.monetizeProduct = monetizeProduct;
	}

	public Syndication getMonetizeSyndication() {
		return monetizeSyndication;
	}

	public void setMonetizeSyndication(final Syndication monetizeSyndication) {
		this.monetizeSyndication = monetizeSyndication;
	}

	public String getMonetizeTitle() {
		return monetizeTitle;
	}

	public void setMonetizeTitle(final String monetizeTitle) {
		this.monetizeTitle = monetizeTitle;
	}

	public String getMonetizeDescription() {
		return monetizeDescription;
	}

	public void setMonetizeDescription(final String monetizeDescription) {
		this.monetizeDescription = monetizeDescription;
	}

	public String getMonetizeId() {
		return monetizeId;
	}

	public void setMonetizeId(final String monetizeId) {
		this.monetizeId = monetizeId;
	}

	public String getMonetizeNotes() {
		return monetizeNotes;
	}

	public void setMonetizeNotes(final String monetizeNotes) {
		this.monetizeNotes = monetizeNotes;
	}

	public String getMonetizeTmsid() {
		return monetizeTmsid;
	}

	public void setMonetizeTmsid(final String monetizeTmsid) {
		this.monetizeTmsid = monetizeTmsid;
	}

	public String getMonetizeIsan() {
		return monetizeIsan;
	}

	public void setMonetizeIsan(final String monetizeIsan) {
		this.monetizeIsan = monetizeIsan;
	}

	public String getMonetizeEidr() {
		return monetizeEidr;
	}

	public void setMonetizeEidr(final String monetizeEidr) {
		this.monetizeEidr = monetizeEidr;
	}

	public String getMonetizeTitleepisode() {
		return monetizeTitleepisode;
	}

	public void setMonetizeTitleepisode(final String monetizeTitleepisode) {
		this.monetizeTitleepisode = monetizeTitleepisode;
	}

	public String getMonetizeSeasonNb() {
		return monetizeSeasonNb;
	}

	public void setMonetizeSeasonNb(final String monetizeSeasonNb) {
		this.monetizeSeasonNb = monetizeSeasonNb;
	}

	public String getMonetizeEpisodeNb() {
		return monetizeEpisodeNb;
	}

	public void setMonetizeEpisodeNb(final String monetizeEpisodeNb) {
		this.monetizeEpisodeNb = monetizeEpisodeNb;
	}

	public ClaimType getMonetizeClaimtype() {
		return monetizeClaimtype;
	}

	public void setMonetizeClaimtype(final ClaimType monetizeClaimtype) {
		this.monetizeClaimtype = monetizeClaimtype;
	}

	public ClaimOption getMonetizeClaimoption() {
		return monetizeClaimoption;
	}

	public void setMonetizeClaimoption(final ClaimOption monetizeClaimoption) {
		this.monetizeClaimoption = monetizeClaimoption;
	}

	public Asset getMonetizeAsset() {
		return monetizeAsset;
	}

	public void setMonetizeAsset(final Asset monetizeAsset) {
		this.monetizeAsset = monetizeAsset;
	}

	public Boolean getMonetizePartner() {
		return monetizePartner;
	}

	public void setMonetizePartner(final Boolean monetizePartner) {
		this.monetizePartner = monetizePartner;
	}
}
