package org.chaosfisch.youtubeuploader.db.validation;

public enum UploadValidationCode {
	UPLOAD_NULL, PLAYLISTS_NULL, ACCOUNT_NULL, FILE_NULL, TITLE_NULL, CATEGORY_NULL, DESCRIPTION_NULL, TITLE_ILLEGAL, DESCRIPTION_LENGTH, DESCRIPTION_ILLEGAL, TAGS_ILLEGAL, THUMBNAIL_SIZE;
}
